import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../components/nav.js";
import Cards from "../components/cards.js";
import News from "../components/newsletter.js";


export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>AniZone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <center><h2>Welcome to AniZone!</h2></center>
      <Cards/>
      <News />
    </div>
  )
}
